# Copyright (c) 2026 Sameer Al Sahab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Galaxy S21 Ultra 5G config
CODENAME="p3q"
DEVICE_VNDK_VERSION="30"
PLATFORM="sm_8350"

# Stock firmware details
STOCK_MODEL="SM-G9980"
STOCK_CSC="TGY"
STOCK_IMEI="354203115858203"

# Source firmware details
MODEL="SM-S9080"
CSC="TGY"
IMEI="350272254378301"

# Extra firmware (Optional) details
EXTRA_MODEL=""
EXTRA_CSC=""
EXTRA_IMEI=""

# Output
FILESYSTEM="erofs"

#Display
DEVICE_DISPLAY_HFR_MODE="3"
DEVICE_DISPLAY_REFRESH_RATE_VALUES_HZ="60,48,96,120"

#
# The following values are auto generated by auto_gen.sh.
# Manually uncomment and set values here to override default stock values.
#

###
# DEVICE_MODEL_NAME="Galaxy S21 Ultra 5G"       # Brand name from settings config
# DEVICE_SIOP_POLICY_FILENAME=""                # Thermal/SIOP policy filename

### Display
# DEVICE_HAVE_HIGH_REFRESH_RATE=""              # Device have high refresh rate or not
# DEVICE_DEFAULT_REFRESH_RATE=""                # Initial boot refresh rate
# DEVICE_HAVE_QHD_PANEL=""                      # True if QHD display device
# DEVICE_HAVE_AMOLED_DISPLAY=""                 # True if amoled display device
# DEVICE_AUTO_BRIGHTNESS_LEVEL=""               # Light sensor behavior
# DEVICE_MDNIE_MODE="65303"                     # Samsung mDnie color profile

### Audio
# DEVICE_HAVE_DUAL_SPEAKER=""                   # true for Stereo, false for Mono

### Extra features
# DEVICE_HAVE_SPEN_SUPPORT=""                   # Device have SPen support
DEVICE_HAVE_ESIM_SUPPORT="true"
DEVICE_HAVE_NPU="true"

### Build Properties
# DEVICE_FIRST_API_VERSION=""                   # ro.vendor.build.version.release
# DEVICE_FIRST_SDK_VERSION=""                   # ro.vendor.build.version.sdk
# DEVICE_VNDK_VERSION=""                        # VNDK version
# DEVICE_SINGLE_SYSTEM_IMAGE=""                 # ro.product.system.device

### External
# DEVICE_FINGERPRINT_SENSOR_TYPE=""             # Biometric sensor type
# DEVICE_HAVE_LEGACY_FACE_HAL=""                # Have legacy Samsung 2.0 biometric face libraries
