# ==============================================================================
# Patch: Camera HAL Cleanup & Injection (AstroROM style)
# Context:
#   - Removes outdated system camera libs
#   - Injects stable camera libs from stock, p3q, r9q firmware
#   - Registers context for proper packaging and HAL execution
# ==============================================================================

LOG_BEGIN "Fixing Camera HAL..."

# Remove outdated system camera libs
LOG_INFO "Removing outdated system camera libraries..."
SILENT REMOVE "system" "lib/FrcMcWrapper.so"
SILENT REMOVE "system" "lib/libFrucPSVTLib.so"
SILENT REMOVE "system" "lib/libSemanticMap_v1.camera.samsung.so"
SILENT REMOVE "system" "lib/libSlowShutter-core.so"
SILENT REMOVE "system" "lib/libaifrc.aidl.quram.so"
SILENT REMOVE "system" "lib/libaifrcInterface.camera.samsung.so"
SILENT REMOVE "system" "lib/libmcaimegpu.samsung.so"
SILENT REMOVE "system" "lib/vendor.samsung.hardware.frcmc-V1-ndk.so"
SILENT REMOVE "system" "lib64/FrcMcWrapper.so"
SILENT REMOVE "system" "lib64/libAEBHDR_wrapper.camera.samsung.so"
SILENT REMOVE "system" "lib64/libAIQSolution_MPISingleRGB40.camera.samsung.so"
SILENT REMOVE "system" "lib64/libBestPhoto.camera.samsung.so"
SILENT REMOVE "system" "lib64/libDocDeblur.camera.samsung.so"
SILENT REMOVE "system" "lib64/libDocObjectRemoval.camera.samsung.so"
SILENT REMOVE "system" "lib64/libDocObjectRemoval.enhanceX.samsung.so"
SILENT REMOVE "system" "lib64/libDualCamBokehCapture.camera.samsung.so"
SILENT REMOVE "system" "lib64/libFaceRecognition.arcsoft.so"
SILENT REMOVE "system" "lib64/libFrucPSVTLib.so"
SILENT REMOVE "system" "lib64/libImageSegmenter_v1.camera.samsung.so"
SILENT REMOVE "system" "lib64/libMPISingleRGB40.camera.samsung.so"
SILENT REMOVE "system" "lib64/libMPISingleRGB40Tuning.camera.samsung.so"
SILENT REMOVE "system" "lib64/libPetClustering.camera.samsung.so"
SILENT REMOVE "system" "lib64/libRelighting_API.camera.samsung.so"
SILENT REMOVE "system" "lib64/libSemanticMap_v1.camera.samsung.so"
SILENT REMOVE "system" "lib64/libSlowShutter-core.so"
SILENT REMOVE "system" "lib64/libacz_hhdr.arcsoft.so"
SILENT REMOVE "system" "lib64/libae_bracket_hdr.arcsoft.so"
SILENT REMOVE "system" "lib64/libaiclearzoom_raw.arcsoft.so"
SILENT REMOVE "system" "lib64/libaiclearzoomraw_wrapper_v1.camera.samsung.so"
SILENT REMOVE "system" "lib64/libaifrc.aidl.quram.so"
SILENT REMOVE "system" "lib64/libaifrcInterface.camera.samsung.so"
SILENT REMOVE "system" "lib64/libarcsoft_dualcam_portraitlighting.so"
SILENT REMOVE "system" "lib64/libarcsoft_single_cam_glasses_seg.so"
SILENT REMOVE "system" "lib64/libdualcam_refocus_image.so"
SILENT REMOVE "system" "lib64/libdvs.camera.samsung.so"
SILENT REMOVE "system" "lib64/libfrtracking_engine.arcsoft.so"
SILENT REMOVE "system" "lib64/libhigh_dynamic_range_bokeh.so"
SILENT REMOVE "system" "lib64/libhybridHDR_wrapper.camera.samsung.so"
SILENT REMOVE "system" "lib64/libhybrid_high_dynamic_range.arcsoft.so"
SILENT REMOVE "system" "lib64/libmcaimegpu.samsung.so"
SILENT REMOVE "system" "lib64/libscalenetpkg.so"
SILENT REMOVE "system" "lib64/libstartrail.camera.samsung.so"
SILENT REMOVE "system" "lib64/libsuperresolution_raw.arcsoft.so"
SILENT REMOVE "system" "lib64/libsuperresolutionraw_wrapper_v2.camera.samsung.so"
SILENT REMOVE "system" "lib64/libtensorflowLite2_11_0_dynamic_camera.so"
SILENT REMOVE "system" "lib64/vendor.samsung.hardware.frcmc-V1-ndk.so"
SILENT REMOVE "system" "lib64/libenn_wrapper_system.so"
SILENT REMOVE "system" "lib64/libpic_best.arcsoft.so"
SILENT REMOVE "system" "lib64/libarcsoft_dualcam_portraitlighting.so"
SILENT REMOVE "system" "lib64/libdualcam_refocus_gallery_54.so"
SILENT REMOVE "system" "lib64/libhybrid_high_dynamic_range.arcsoft.so"
SILENT REMOVE "system" "lib64/libae_bracket_hdr.arcsoft.so"
SILENT REMOVE "system" "lib64/libface_recognition.arcsoft.so"
SILENT REMOVE "system" "lib64/libDualCamBokehCapture.camera.samsung.so"

LOG_INFO "Outdated camera libraries removed successfully"

LOG_BEGIN "Adding Camera Libraries..."

# Inject stable camera libs from stock firmware
LOG_INFO "Injecting camera libraries from stock firmware..."
ADD_FROM_FW "stock" "system" "etc/public.libraries-arcsoft.txt"
ADD_FROM_FW "stock" "system" "lib64/libAiSolution_wrapper_v1.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libBright_core.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libFacePreProcessing.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libFaceRestoration.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libFace_Landmark_API.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libFace_Landmark_Engine.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libHprFace_GAE_api.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libHpr_RecFace_dl_v1.0.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libHpr_RecGAE_cvFeature_v1.0.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libHpr_TaskFaceClustering_hierarchical_v1.0.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libImageCropper.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libImageTagger.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libPortraitDistortionCorrection.arcsoft.so"
ADD_FROM_FW "stock" "system" "lib64/libPortraitDistortionCorrectionCali.arcsoft.so"
ADD_FROM_FW "stock" "system" "lib64/libUltraWideDistortionCorrection.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libWideDistortionCorrection.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libhumantracking_util.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libhumantracking.arcsoft.so"
ADD_FROM_FW "stock" "system" "lib64/liblow_light_hdr.arcsoft.so"
ADD_FROM_FW "stock" "system" "lib64/libsaiv_HprFace_cmh_support_jni.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libtensorflowLite.dynamic_viewing.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libtensorflowlite_jni_r2.6.so"

LOG_INFO "Camera libraries injected successfully"

# Register context for injected camera libs
LOG_INFO "Registering context for camera libraries..."
ADD_CONTEXT "system" "etc/public.libraries-arcsoft.txt" "system_file"
ADD_CONTEXT "system" "lib64/libAiSolution_wrapper_v1.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libBright_core.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libFacePreProcessing.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libFaceRestoration.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libFace_Landmark_API.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libFace_Landmark_Engine.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libHprFace_GAE_api.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libHpr_RecFace_dl_v1.0.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libHpr_RecGAE_cvFeature_v1.0.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libHpr_TaskFaceClustering_hierarchical_v1.0.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libImageCropper.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libImageTagger.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libPortraitDistortionCorrection.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/libPortraitDistortionCorrectionCali.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/libUltraWideDistortionCorrection.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libWideDistortionCorrection.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libhumantracking_util.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libhumantracking.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/liblow_light_hdr.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/libsaiv_HprFace_cmh_support_jni.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libtensorflowLite.dynamic_viewing.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libtensorflowlite_jni_r2.6.so" "system_file"

LOG_END "Camera libraries patch applied successfully"

LOG_BEGIN "Patching Camera Processing..."

# MultiFrame Processing (Stock firmware)
LOG_INFO "Injecting MultiFrame Processing libs from y2q firmware..."
ADD_FROM_FW "stock" "system" "lib64/libMultiFrameProcessing30.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libMultiFrameProcessing30.snapwrapper.camera.samsung.so"
ADD_FROM_FW "stock" "system" "lib64/libMultiFrameProcessing30Tuning.camera.samsung.so"

ADD_CONTEXT "system" "lib64/libMultiFrameProcessing30.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libMultiFrameProcessing30.snapwrapper.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libMultiFrameProcessing30Tuning.camera.samsung.so" "system_file"

LOG_INFO "MultiFrame Processing libs injected successfully"

# HDR & Super Resolution (p3q firmware)
LOG_INFO "Injecting HDR and Super Resolution libs from p3q firmware..."
ADD_FROM_FW "p3q" "system" "lib64/libhigh_dynamic_range.arcsoft.so"
ADD_FROM_FW "p3q" "system" "lib64/liblow_light_hdr.arcsoft.so"
ADD_FROM_FW "p3q" "system" "lib64/libhigh_res.arcsoft.so"
ADD_FROM_FW "p3q" "system" "lib64/libsnap_aidl.snap.samsung.so"
ADD_FROM_FW "p3q" "system" "lib64/libsuperresolution.arcsoft.so"
ADD_FROM_FW "p3q" "system" "lib64/libsuperresolution_raw.arcsoft.so"
ADD_FROM_FW "p3q" "system" "lib64/libsuperresolution_wrapper_v2.camera.samsung.so"
ADD_FROM_FW "p3q" "system" "lib64/libsuperresolutionraw_wrapper_v2.camera.samsung.so"

ADD_CONTEXT "system" "lib64/libeden_wrapper_system.so" "system_file"
ADD_CONTEXT "system" "lib64/libhigh_dynamic_range.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/liblow_light_hdr.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/libhigh_res.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/libsnap_aidl.snap.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libsuperresolution.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/libsuperresolution_raw.arcsoft.so" "system_file"
ADD_CONTEXT "system" "lib64/libsuperresolution_wrapper_v2.camera.samsung.so" "system_file"
ADD_CONTEXT "system" "lib64/libsuperresolutionraw_wrapper_v2.camera.samsung.so" "system_file"

LOG_INFO "HDR and Super Resolution libs injected successfully"

# HDR10+ (r9q firmware)
LOG_INFO "Injecting HDR10+ support libs from r9q firmware..."
ADD_FROM_FW "r9q" "system" "lib/libstagefright.so"
ADD_FROM_FW "r9q" "vendor" "lib64/X12QS_libTsAe.so"

ADD_CONTEXT "system" "lib/libstagefright.so" "system_file"
ADD_CONTEXT "vendor" "lib64/X12QS_libTsAe.so" "vendor_file"

LOG_INFO "HDR10+ support libs injected successfully"

LOG_END "Camera Processing & HDR10+ patch applied successfully"
