# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ⚡ AstroROM Floating Features ⚡
# Device: Galaxy S20+ (y2q)
# Firmware Base: OneUI 8.0 / Android 16
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 🔋 Battery
FF "BATTERY_SUPPORT_PD_HV" "TRUE"
FF "BATTERY_SUPPORT_PASS_THROUGH" ""

# 🎙️ Bixby
FF "BIXBY_CONFIG_BARGEIN_FUNCTION" "0"
FF "BIXBY_CONFIG_BARGEIN_PARAM_MODE" ""
FF "BIXBY_CONFIG_CUSTOM_FIRMWARE" "0"
FF "BIXBY_SUPPORT_CUSTOM_WAKEUP" "2"
FF "BIXBY_SUPPORT_USERKWD_WAKEUP" "TRUE"

# 📡 NFC
FF "FRAMEWORK_CONFIG_NFC_LED_COVER_LEVEL" "80"

# 🕒 AOD
FF "LCD_CONFIG_AOD_BRIGHTNESS_ANIMATION" "0"
FF "LCD_CONFIG_AOD_FULLSCREEN" "1"

# 🎧 Audio
FF "AUDIO_CONFIG_SOUNDALIVE_VERSION" "eq_custom,uhq_onoff,karaoke,adapt,spk_stereo,dvfs_25_percent"
FF "AUDIO_SUPPORT_VOIP_VIA_SMART_MONITOR" ""
FF "AUDIO_CONFIG_VOLUMEMONITOR_GAIN" "3"

# 🌈 Display
FF "LCD_SUPPORT_EXTRA_BRIGHTNESS" "false"
FF "LCD_SUPPORT_BLUE_FILTER_ADAPTIVE_MODE" "1"
FF "LCD_CONFIG_VIVIDNESS" "0"
FF "LCD_CONFIG_VIVIDPLUS" "0"
FF "LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS" "4"
FF "LCD_CONFIG_HFR_DEFAULT_REFRESH_RATE" "120"
FF "LCD_CONFIG_HFR_MODE" "2"
FF "LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE" "60,96,120"
FF "LOCKSCREEN_CONFIG_PUNCHHOLE_VI" "face,pos:0.5:0.01875,size:0.0833:0.0375,type:circle"
FF "LOCKSCREEN_CONFIG_SUBDISPLAY_POLICY" ""

# 📱 Device Info
FF "SETTINGS_CONFIG_BRAND_NAME" "Galaxy S20+ 5G"
FF "SETTINGS_CONFIG_FCC_ID" "A3LSMG986N"
FF "SETTINGS_CONFIG_ELECTRIC_RATED_VALUE" "DC 9 V; 2.77 A / 10 v; 4.50 A"
FF "SYSTEM_CONFIG_SIOP_POLICY_FILENAME" "siop_y2q_sm8250"

# 📷 Camera
FF "SAIV_CONFIG_MIDAS" "UPSCALE,LOWLIGHT,HDR,DEBLUR,MOIRE,DENOISE_DEBLUR,UPSCALE_DEBLUR,PHOTOPOLISH,SHADOW,REFLECTION,UWDC"
FF "CAMERA_SUPPORT_SUPER_NIGHT_DRAFT_RAW" ""
FF "CAMERA_CONFIG_AIFRC_SPEC" ""
FF "CAMERA_CONFIG_AUTOFRAMING" ""
FF "CAMERA_CONFIG_CAMID_TELE_BINNING" "50"
FF "CAMERA_CONFIG_CAMID_TELE_STANDARD_CROP" "52"
FF "CAMERA_CONFIG_CAMID_TELE2" "-1"
FF "CAMERA_CONFIG_CAMID_UW" "2"
FF "CAMERA_CONFIG_CAMID_WIDE" "0"
FF "CAMERA_CONFIG_MEMORY_USAGE_LEVEL" "3"
FF "CAMERA_CONFIG_PERSONALIZATION" "CoolOriWarm"
FF "CAMERA_CONFIG_GPPM_SOLUTIONS" "startrail,motionclipper"
FF "CAMERA_CONFIG_IS_GPPM_1_0_ENABLED" "TRUE"
FF "CAMERA_CONFIG_WINE_DETECTOR" "OFF"
FF "CAMERA_GRAW_CONFIG_MFP_PIPELINE_MODE" "V1"
FF "CAMERA_CONFIG_SDK_FEATURE_INFO" "version2,super_night,preview_dis,video_hdr,smooth_zoom,logical_rear_camera:camera_id=20"
FF "CAMERA_CONFIG_UW_DISTORTION_CORRECTION" "0,109,2,19010101,0,0,0,0,48,0"
FF "CAMERA_CONFIG_VENDOR_LIB_INFO" "beauty.samsung.v4,food.samsung.v1,mfhdr.arcsoft.v4,image_enhance.arcsoft.v1,llhdr.arcsoft.v4,dual_bokeh.samsung.v1_1,super_night.mpi.v2,super_resolution.arcsoft.v2_1,scene_detection.samsung.v1,face_landmark.arcsoft.v2_1,facial_attribute.samsung.v1,smart_scan.samsung.v2,single_bokeh.samsung.v2,high_res.arcsoft.v1,selfie_correction.samsung.v1,event_detection.samsung.v2,swuwdc.arcsoft.v1,facial_restoration.arcsoft.v1,human_tracking_hand.arcsoft.v4,fr_tracking.arcsoft.v1,localtm.samsung.v1_1,image_codec.samsung.v1"
FF "CAMERA_CONFIG_WIDE_DISTORTION_CORRECTION" "0,0,0,0,0,0,0,0,0,0"
FF "CAMERA_CONFIG_HIGH_RESOLUTION_MAX_CAPTURE" "-1"
FF "CAMERA_CONFIG_MOTIONPHOTO_CAPTURE_MODE" "[[3,1]]"
FF "CAMERA_SUPPORT_VDIS_ON_MOTIONPHOTO" "TRUE"
FF "CAMERA_SUPPORT_30FPS_ALL_PORTRAITVIDEO" ""
FF "CAMERA_SUPPORT_4K_PORTRAITVIDEO" ""
FF "CAMERA_SUPPORT_AIFRC" ""
FF "CAMERA_SUPPORT_AI_HIGH_RESOLUTION" "true"
FF "CAMERA_SUPPORT_AI_HIGH_RESOLUTION_DRAFT_DOWNSCALE" "true"
FF "CAMERA_SUPPORT_DUAL_PORTRAITVIDEO" ""
FF "CAMERA_SUPPORT_EDITABLE_PORTRAITVIDEO" ""
FF "CAMERA_SUPPORT_HIGH_RESOLUTION_SWBINNING" "true"
FF "CAMERA_SUPPORT_HYPERLAPSE_VDISONOFF" ""
FF "CAMERA_SUPPORT_LOGICAL_CAMERA" "TRUE"
FF "CAMERA_SUPPORT_PORTRAIT_INTELLIGENT_OPTIMIZATION_AI_ISP" "true"
FF "CAMERA_SUPPORT_PRO_RGB_CONVERSION" ""
FF "CAMERA_SUPPORT_SEAMLESS_PORTRAITVIDEO" ""
FF "CAMERA_SUPPORT_VDIS_ON_MOTIONPHOTO" ""
FF "CAMERA_SUPPORT_VDIS_PORTRAITVIDEO" ""
FF "COMMON_CONFIG_SWLENS_DISTORTION_CORRECTION" "unbound,IMX563"
FF "GALLERY_CONFIG_AI_EXPANSION" ""
FF "GALLERY_CONFIG_PET_CLUSTER_VERSION" ""
FF "CAMERA_CONFIG_NIGHT_FRONT_DISPLAY_FLASH_TRANSPARENT" "85"
FF "CAMERA_CONFIG_MYFILTER" "1,3,4"
FF "CAMERA_CONFIG_LOG_VIDEO" "v1.0"
FF "MMFW_SUPPORT_AI_UPSCALER" "TRUE"

# ⚙️ Misc
FF "GRAPHICS_SUPPORT_TOUCH_FAST_RESPONSE" "true"
FF "SYSTEM_SUPPORT_LOW_HEAT_MODE" "true"
